name: 3.3.x | Framework Smoke Tests | Webmvc Jetty
on:
  schedule:
    - cron : '10 0 * * *'
  workflow_dispatch:
jobs:
  webmvc_jetty_test:
    name: Webmvc Jetty Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: framework:webmvc-jetty
      task: test
  webmvc_jetty_app_test:
    name: Webmvc Jetty App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: framework:webmvc-jetty
      task: appTest
  webmvc_jetty_checkpoint_restore_app_test:
    name: Webmvc Jetty Checkpoint Restore App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: framework:webmvc-jetty
      task: checkpointRestoreAppTest
