name: 3.3.x | Framework Smoke Tests | Webclient Netty
on:
  schedule:
    - cron : '10 0 * * *'
  workflow_dispatch:
jobs:
  webclient_netty_app_test:
    name: Webclient Netty App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: framework:webclient-netty
      task: appTest
  webclient_netty_checkpoint_restore_app_test:
    name: Webclient Netty Checkpoint Restore App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: framework:webclient-netty
      task: checkpointRestoreAppTest
