name: 3.3.x | Integration Smoke Tests | Spring Kafka
on:
  schedule:
    - cron : '10 0 * * *'
  workflow_dispatch:
jobs:
  spring_kafka_app_test:
    name: Spring Kafka App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: integration:spring-kafka
      task: appTest
  spring_kafka_checkpoint_restore_app_test:
    name: Spring Kafka Checkpoint Restore App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: integration:spring-kafka
      task: checkpointRestoreAppTest
