name: 3.3.x | Boot Smoke Tests | Actuator Webflux
on:
  schedule:
    - cron : '10 0 * * *'
  workflow_dispatch:
jobs:
  actuator_webflux_app_test:
    name: Actuator Webflux App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: boot:actuator-webflux
      task: appTest
  actuator_webflux_checkpoint_restore_app_test:
    name: Actuator Webflux Checkpoint Restore App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: 3.3.x
      project: boot:actuator-webflux
      task: checkpointRestoreAppTest
