name: 3.4.x | Data Smoke Tests | Data Jdbc
on:
  schedule:
    - cron : '20 0 * * *'
  workflow_dispatch:
jobs:
  data_jdbc_app_test:
    name: Data Jdbc App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: main
      project: data:data-jdbc
      task: appTest
  data_jdbc_checkpoint_restore_app_test:
    name: Data Jdbc Checkpoint Restore App Test
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-lifecycle-smoke-tests
      checkout_ref: main
      project: data:data-jdbc
      task: checkpointRestoreAppTest
